---
# tasks file for podman-systemd-simple
- name: Create systemd service unit file for pod or container
  vars:
    # only literal 'pod' and 'container' strings are good
    prefix: "{{ type }}"
    service_unit: "{{ prefix }}-{{ container_name }}.service"
  block:
    - name: Generate systemd units by podman
      command:
        cmd: podman generate systemd -f -n -t "{{ container_stop_timeout }}" "{{ container_name }}"
        chdir: "{{ service_files_dir }}"

    - name: Check that generated service unit exists
      ansible.builtin.stat:
        path: "{{ service_files_dir }}/{{ service_unit }}"
      register: stat_result

    - name: Enable systemd service unit
      ansible.builtin.systemd:
        name: "{{ service_unit }}"
        state: "{{ service_state }}"
        daemon_reload: yes
        enabled: "{{ service_enabled }}"
      when: stat_result.stat.exists
