---
# defaults file for kibana
state: "started"
recreate: "no"
firewalld_zone: "public"
firewalld_enabled: "no"
timezone: "Europe/Budapest"

# persistent directories
kibana_config: "{{ container_conf_dir }}/{{inventory_hostname_short}}.kibana_{{kibana.instance_name}}"
kibana_data: "{{ container_data_dir }}/{{inventory_hostname_short}}.kibana_{{kibana.instance_name}}"

# container defaults
kibana_image: "docker.elastic.co/kibana/kibana"
kibana_version: "{{ elk_version | default('7.14.1')}}"

kibana_pod_name: "kibana"
kibana_pod_network: "host"

kibana_fqdn: "{{vault_kibana_fqdn | default('example.com')}}"

# service level settings (shared between role elasticsearch and role kibana)
kibana_system_password: "{{ vault_kibana_system_password | default('changeMe') }}"

kibana:
  ip_address: "0.0.0.0"
  java_opts: "-Xms2g -Xmx2g"
  instance_name: "internal01"
  memory_limit: 2g
  cpu_limit: 1
  ports:
    - "5601"

# This setting is is required for enabling API access
kibana_security_encryptionkey: "{{vault_kibana_security_encryptionkey}}"
kibana_savedobjects_encryptionkey: "{{vault_kibana_savedobjects_encryptionkey}}"
kibana_reporting_encryptionkey: "{{vault_kibana_reporting_encryptionkey}}"

# KIBANA related certificates:
# SHOULD BE ACCESSIBLE FOR BEATS TOO
# what about putting into "group_vars/elastic_stack"
server_ssl_ca: "{{ vault_server_ssl_ca }}"
server_ssl_cert_format: "pkcs12"
server_ssl_keystore: "{{ vault_server_ssl_keystore | default('na') }}"
server_ssl_keystore_password: "{{ vault_server_ssl_keystore_password }}"
server_ssl_cert: "{{ vault_server_ssl_cert | default('na') }}"
server_ssl_key: "{{ vault_server_ssl_key | default('na') }}"
elasticsearch_ssl_ca: "{{ vault_elasticsearch_ssl_ca }}"
elasticsearch_ssl_verification_mode: "certificate"
